# Generated by Django 3.2.3 on 2021-05-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Flooid Website', max_length=255),
        ),
    ]
